sudo: required
language: cpp
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libcurl4-gnutls-dev libmms-dev libglib2.0-dev zlib1g-dev pkg-config
  - wget http://mediaarea.net/download/binary/libzen0/0.4.32/libzen0_0.4.32-1_amd64.xUbuntu_12.04.deb
  - sudo dpkg -i libzen0_0.4.32-1_amd64.xUbuntu_12.04.deb
  - wget http://mediaarea.net/download/binary/libzen0/0.4.32/libzen-dev_0.4.32-1_amd64.xUbuntu_12.04.deb
  - sudo dpkg -i libzen-dev_0.4.32-1_amd64.xUbuntu_12.04.deb
script: cd Project/GNU/Library/ && ./autogen.sh && ./configure && make
